## 20240623.australiaeast-dev.plan.01
name: "$(Date:yyyyMMdd).${{ parameters.locationEnvironmentName }}-${{ parameters.environmentName }}.${{ parameters.terraformAction }}.$(rev:rr)"

pr: none
trigger: none

parameters:
- name: locationEnvironmentName
  displayName: Location/Environment
  type: string
  values:
    - australiaeast-dev

- name: environmentName
  displayName: Environment
  type: string
  values:
    - dev1
    - dev2

- name: terraformAction
  displayName: Terraform Action
  type: string
  default: plan
  values:
    - plan
    - apply
    - destroy

variables:
- name: terraformExecutionDirectory
  value: '$(Build.SourcesDirectory)/environments/${{ parameters.locationEnvironmentName }}/${{ parameters.environmentName }}'

steps:
- template: templates/tf-action-steps.yml
  parameters:
    terraformAction: ${{ parameters.terraformAction }}
    terraformExeuctionDirectory: '$(terraformExecutionDirectory)'
    backendServiceArm: 'jt-payg-ado'
    backendAzureRmResourceGroupName: 'jt-tfstate-rg'
    backendAzureRmStorageAccountName: 'jttfstatestorage'
    backendAzureRmContainerName: 'tfstate-dev'
    backendAzureRmKey: '${{ parameters.locationEnvironmentName }}/${{ parameters.environmentName }}.tfstate'
